/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BenchmarkDetail: typeof import('./src/components/BenchmarkDetail.vue')['default']
    BenchmarkList: typeof import('./src/components/BenchmarkList.vue')['default']
    BenchmarkStatusChip: typeof import('./src/components/BenchmarkStatusChip.vue')['default']
    Button: typeof import('primevue/button')['default']
    CopyToClipboardButton: typeof import('./src/components/CopyToClipboardButton.vue')['default']
    ErrorMessage: typeof import('./src/components/ErrorMessage.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    InstanceCardList: typeof import('./src/components/InstanceCardList.vue')['default']
    InstanceStatusChip: typeof import('./src/components/InstanceStatusChip.vue')['default']
    MainButton: typeof import('./src/components/MainButton.vue')['default']
    MainSwitch: typeof import('./src/components/MainSwitch.vue')['default']
    PageTitle: typeof import('./src/components/PageTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeamManagement: typeof import('./src/components/TeamManagement.vue')['default']
    UserAvatar: typeof import('./src/components/UserAvatar.vue')['default']
  }
}
