version: "2"
linters:
  enable:
    - revive
    - wrapcheck
  settings:
    wrapcheck:
      extra-ignore-sigs:
        - (github.com/labstack/echo/v4.Context).
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - server/handler/openapi
      - .*/mock$
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - server/handler/openapi
      - .*/mock$
      - third_party$
      - builtin$
      - examples$
