# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: piscon-runner

builds:
  - id: runner
    main: ./cmd/runner
    binary: runner
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: runner
    ids:
      - runner
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt
