services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: portal
    ports:
      - 3306:3306
    volumes:
      - ./server/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  portal:
    image: ghcr.io/traPtitech/piscon-portal-v2/portal:main
    ports:
      - 8080:8080
      - 50051:50051
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/api/health"]
      interval: 10s
      timeout: 10s
      retries: 5

  client:
    image: ghcr.io/traPtitech/piscon-portal-v2/client:main
    ports:
      - 3000:80
    depends_on:
      portal:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  db_data:
    driver: local
