version: "3"

tasks:
  run-server:
    dotenv:
      - .env
    deps:
      - up-db
    cmds:
      - go run cmd/server/main.go

  test:
    cmds:
      - go test -cover -race ./...

  go:gen:
    cmds:
      - task: up-db
      - go generate ./...
    sources:
      - openapi/openapi.yml
      - server/bobgen.yaml
      - server/ogen.yaml
      - server/schema.sql
      - runner/benchmarker/**.go
      - runner/portal/**.go
    generates:
      - server/openapi/*.go
      - server/models/**/*.go

  proto:gen:
    cmds:
      - buf generate
    sources:
      - proto/**/*.proto
    generates:
      - gen/**

  gen:
    cmds:
      - task: go:gen
      - task: proto:gen

  up-db:
    cmds:
      - docker compose up -d --wait db

  down-db:
    cmds:
      - docker compose down db
