version: "3"

env:
  GOEXPERIMENT: "synctest"

tasks:
  run-server:
    dotenv:
      - .env
    deps:
      - up-db
    cmds:
      - go run cmd/server/main.go

  test:
    cmds:
      - go test -cover -race ./...

  go:gen:
    cmds:
      - task: up-db
      - go generate ./...
    sources:
      - openapi/openapi.yml
      - server/bobgen.yaml
      - server/ogen.yaml
      - server/schema.sql
    generates:
      - server/openapi/*.go
      - server/models/**/*.go

  runner:gen:
    cmds:
      - go generate ./runner/...
    sources:
      - runner/portal/**.go
      - runner/benchmarker/**.go
    generates:
      - runner/portal/mock/**.go
      - runner/benchmarker/mock/**.go

  proto:gen:
    cmds:
      - buf generate
    sources:
      - proto/**/*.proto
    generates:
      - gen/**

  gen:
    cmds:
      - task: go:gen
      - task: runner:gen
      - task: proto:gen

  up-db:
    cmds:
      - docker compose up -d --wait db

  down-db:
    cmds:
      - docker compose down db

  lint:
    cmd: golangci-lint run ./...

  lint:fix:
    cmd: golangci-lint run --fix ./...
