openapi: 3.0.3
info:
  title: "piscon-portal-v2"
  version: "v0.0.0"
servers:
  - url: "http://localhost:8080/api"
    description: "Local server"

tags:
  - name: "oauth2"
    description: "OAuth2を使った部員の認証"

paths:
  /oauth2/code:
    get:
      operationId: "getOauth2Code"
      tags:
        - "oauth2"
      summary: "OAuth2認証コードの取得・traQの認可ページにリダイレクト"
      description: "OAuth2の認証に必要なCode Verifierを生成し、traQの認可ページにリダイレクトします。"
      responses:
        303:
          description: "traQの認可ページにリダイレクトします。"
          headers:
            Location:
              schema:
                type: "string"
                format: "uri"
                example: "https://q.trap.jp/oauth2/authorize?response_type=code&client_id=client_id&redirect_uri=http://localhost:8080/api/oauth2/callback&state=state&code_challenge=code_challenge&code_challenge_method=S256"
        500:
          $ref: "#/components/responses/InternalServerError"

  /oauth2/callback:
    get:
      operationId: "getOauth2Callback"
      tags:
        - "oauth2"
      summary: "traQからのリダイレクト"
      description: "traQ上での認証後にtraQから Authorization Codeがクエリパラメーターにつけられて、 リダイレクトされます。"
      parameters:
        - name: "code"
          in: "query"
          description: "traQからのAuthorization Code"
          required: true
          schema:
            type: "string"
            example: "authorization_code"
      responses:
        200:
          description: "認証に成功しました。"
        400:
          description: "セッションやAuthorization Codeに誤りがあり、認証に失敗しました"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"
                    example: "認証に失敗しました。"
        500:
          $ref: "#/components/responses/InternalServerError"

  /oauth2/logout:
    post:
      summary: "ログアウト"
      description: "ログアウトし、セッションを削除します"
      tags:
        - "oauth2"
      security:
        - UserAuth: []
      operationId: "postOauth2Logout"
      responses:
        200:
          description: "ログアウトしました。"
        400:
          description: "セッションに誤りがあり、認証に失敗しました"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"
                    example: "誤りの内容"
        401:
          $ref: "#/components/responses/Unauthorized"
        500:
          $ref: "#/components/responses/InternalServerError"

components:
  responses:
    Unauthorized:
      description: "Unauthorized"
      content:
        application/json:
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "Unauthorized"
    InternalServerError:
      description: "Internal Server Error"
      content:
        application/json:
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "Internal Server Error"

  securitySchemes:
    UserAuth:
      type: apiKey
      in: cookie
      name: piscon_session
      description: "部員である場合にアクセスできる"
    AdminAuth:
      type: apiKey
      in: cookie
      name: piscon_session
      description: "管理者である場合にアクセスできる"
