[project]
name = "piscon-portal-v2-ansible"
version = "0.1.0"
description = "PISCON Portal v2 and runner provisioning with Ansible"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ansible>=11.7.0",
]

[dependency-groups]
dev = [
    "ansible-lint>=25.6.1",
]
