// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Instances = Table[
	instanceColumns,
	instanceIndexes,
	instanceForeignKeys,
	instanceUniques,
	instanceChecks,
]{
	Schema: "",
	Name:   "instances",
	Columns: instanceColumns{
		ID: column{
			Name:      "id",
			DBType:    "varchar(36)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ProviderInstanceID: column{
			Name:      "provider_instance_id",
			DBType:    "varchar(255)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		TeamID: column{
			Name:      "team_id",
			DBType:    "varchar(36)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		InstanceNumber: column{
			Name:      "instance_number",
			DBType:    "int",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		DeletedAt: column{
			Name:      "deleted_at",
			DBType:    "timestamp",
			Default:   "",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: instanceIndexes{
		PRIMARY: index{
			Type: "BTREE",
			Name: "PRIMARY",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
	},
	PrimaryKey: &constraint{
		Name:    "PRIMARY",
		Columns: []string{"id"},
		Comment: "",
	},

	Comment: "",
}

type instanceColumns struct {
	ID                 column
	ProviderInstanceID column
	TeamID             column
	InstanceNumber     column
	CreatedAt          column
	DeletedAt          column
}

func (c instanceColumns) AsSlice() []column {
	return []column{
		c.ID, c.ProviderInstanceID, c.TeamID, c.InstanceNumber, c.CreatedAt, c.DeletedAt,
	}
}

type instanceIndexes struct {
	PRIMARY index
}

func (i instanceIndexes) AsSlice() []index {
	return []index{
		i.PRIMARY,
	}
}

type instanceForeignKeys struct{}

func (f instanceForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type instanceUniques struct{}

func (u instanceUniques) AsSlice() []constraint {
	return []constraint{}
}

type instanceChecks struct{}

func (c instanceChecks) AsSlice() []check {
	return []check{}
}
