// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Teams = Table[
	teamColumns,
	teamIndexes,
	teamForeignKeys,
	teamUniques,
	teamChecks,
]{
	Schema: "",
	Name:   "teams",
	Columns: teamColumns{
		ID: column{
			Name:      "id",
			DBType:    "varchar(36)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Name: column{
			Name:      "name",
			DBType:    "varchar(255)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: teamIndexes{
		PRIMARY: index{
			Type: "BTREE",
			Name: "PRIMARY",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
	},
	PrimaryKey: &constraint{
		Name:    "PRIMARY",
		Columns: []string{"id"},
		Comment: "",
	},

	Comment: "",
}

type teamColumns struct {
	ID        column
	Name      column
	CreatedAt column
}

func (c teamColumns) AsSlice() []column {
	return []column{
		c.ID, c.Name, c.CreatedAt,
	}
}

type teamIndexes struct {
	PRIMARY index
}

func (i teamIndexes) AsSlice() []index {
	return []index{
		i.PRIMARY,
	}
}

type teamForeignKeys struct{}

func (f teamForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type teamUniques struct{}

func (u teamUniques) AsSlice() []constraint {
	return []constraint{}
}

type teamChecks struct{}

func (c teamChecks) AsSlice() []check {
	return []check{}
}
