---
- name: Make runner directory
  ansible.builtin.file:
    path: /srv/runner
    state: directory
    mode: "0755"
  become: true

- name: Set runner config file
  ansible.builtin.template:
    src: "problems/{{ problem.name }}.yaml.j2"
    dest: /srv/runner/piscon_runner.yaml
    mode: "0644"
  become: true
  notify:
    - Restart runner service

- name: Install runner
  ansible.builtin.command:
    cmd: "go install github.com/traPtitech/piscon-portal-v2/cmd/runner@{{ runner.git_ref }}"
  changed_when: false

- name: Check GOBIN
  ansible.builtin.command:
    cmd: "go env GOBIN"
  register: go_gobin
  changed_when: false

- name: Check GOPATH
  ansible.builtin.command:
    cmd: "go env GOPATH"
  register: go_gopath
  changed_when: false

- name: Create piscon-runner service
  ansible.builtin.template:
    src: piscon-runner.service
    dest: /etc/systemd/system/piscon-runner.service
    mode: "0644"
  vars:
    bin_dir: "{{ go_gobin.stdout if go_gobin.stdout else (go_gopath.stdout + '/bin') }}"
  become: true
  notify:
    - Reload systemd
    - Restart runner service
    - Enable runner service
