// Code generated by BobGen mysql v0.30.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

type Factory struct {
	baseBenchmarkLogMods BenchmarkLogModSlice
	baseBenchmarkMods    BenchmarkModSlice
	baseInstanceMods     InstanceModSlice
	baseSessionMods      SessionModSlice
	baseTeamMods         TeamModSlice
	baseUserMods         UserModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewBenchmarkLog(mods ...BenchmarkLogMod) *BenchmarkLogTemplate {
	o := &BenchmarkLogTemplate{f: f}

	if f != nil {
		f.baseBenchmarkLogMods.Apply(o)
	}

	BenchmarkLogModSlice(mods).Apply(o)

	return o
}

func (f *Factory) NewBenchmark(mods ...BenchmarkMod) *BenchmarkTemplate {
	o := &BenchmarkTemplate{f: f}

	if f != nil {
		f.baseBenchmarkMods.Apply(o)
	}

	BenchmarkModSlice(mods).Apply(o)

	return o
}

func (f *Factory) NewInstance(mods ...InstanceMod) *InstanceTemplate {
	o := &InstanceTemplate{f: f}

	if f != nil {
		f.baseInstanceMods.Apply(o)
	}

	InstanceModSlice(mods).Apply(o)

	return o
}

func (f *Factory) NewSession(mods ...SessionMod) *SessionTemplate {
	o := &SessionTemplate{f: f}

	if f != nil {
		f.baseSessionMods.Apply(o)
	}

	SessionModSlice(mods).Apply(o)

	return o
}

func (f *Factory) NewTeam(mods ...TeamMod) *TeamTemplate {
	o := &TeamTemplate{f: f}

	if f != nil {
		f.baseTeamMods.Apply(o)
	}

	TeamModSlice(mods).Apply(o)

	return o
}

func (f *Factory) NewUser(mods ...UserMod) *UserTemplate {
	o := &UserTemplate{f: f}

	if f != nil {
		f.baseUserMods.Apply(o)
	}

	UserModSlice(mods).Apply(o)

	return o
}

func (f *Factory) ClearBaseBenchmarkLogMods() {
	f.baseBenchmarkLogMods = nil
}

func (f *Factory) AddBaseBenchmarkLogMod(mods ...BenchmarkLogMod) {
	f.baseBenchmarkLogMods = append(f.baseBenchmarkLogMods, mods...)
}

func (f *Factory) ClearBaseBenchmarkMods() {
	f.baseBenchmarkMods = nil
}

func (f *Factory) AddBaseBenchmarkMod(mods ...BenchmarkMod) {
	f.baseBenchmarkMods = append(f.baseBenchmarkMods, mods...)
}

func (f *Factory) ClearBaseInstanceMods() {
	f.baseInstanceMods = nil
}

func (f *Factory) AddBaseInstanceMod(mods ...InstanceMod) {
	f.baseInstanceMods = append(f.baseInstanceMods, mods...)
}

func (f *Factory) ClearBaseSessionMods() {
	f.baseSessionMods = nil
}

func (f *Factory) AddBaseSessionMod(mods ...SessionMod) {
	f.baseSessionMods = append(f.baseSessionMods, mods...)
}

func (f *Factory) ClearBaseTeamMods() {
	f.baseTeamMods = nil
}

func (f *Factory) AddBaseTeamMod(mods ...TeamMod) {
	f.baseTeamMods = append(f.baseTeamMods, mods...)
}

func (f *Factory) ClearBaseUserMods() {
	f.baseUserMods = nil
}

func (f *Factory) AddBaseUserMod(mods ...UserMod) {
	f.baseUserMods = append(f.baseUserMods, mods...)
}
