// Code generated by BobGen mysql v0.34.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import models "github.com/traPtitech/piscon-portal-v2/server/repository/db/models"

type (
	BenchmarksResult = models.BenchmarksResult
	BenchmarksStatus = models.BenchmarksStatus
	InstancesStatus  = models.InstancesStatus
)

func allBenchmarksResult() []BenchmarksResult {
	return models.AllBenchmarksResult()
}

func allBenchmarksStatus() []BenchmarksStatus {
	return models.AllBenchmarksStatus()
}

func allInstancesStatus() []InstancesStatus {
	return models.AllInstancesStatus()
}
