// Code generated by BobGen mysql v0.39.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
	models "github.com/traPtitech/piscon-portal-v2/server/repository/db/models"
)

type TeamMod interface {
	Apply(context.Context, *TeamTemplate)
}

type TeamModFunc func(context.Context, *TeamTemplate)

func (f TeamModFunc) Apply(ctx context.Context, n *TeamTemplate) {
	f(ctx, n)
}

type TeamModSlice []TeamMod

func (mods TeamModSlice) Apply(ctx context.Context, n *TeamTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// TeamTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type TeamTemplate struct {
	ID        func() string
	Name      func() string
	CreatedAt func() time.Time

	r teamR
	f *Factory

	alreadyPersisted bool
}

type teamR struct {
	Users []*teamRUsersR
}

type teamRUsersR struct {
	number int
	o      *UserTemplate
}

// Apply mods to the TeamTemplate
func (o *TeamTemplate) Apply(ctx context.Context, mods ...TeamMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Team
// according to the relationships in the template. Nothing is inserted into the db
func (t TeamTemplate) setModelRels(o *models.Team) {
	if t.r.Users != nil {
		rel := models.UserSlice{}
		for _, r := range t.r.Users {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.TeamID = null.From(o.ID) // h2
				rel.R.Team = o
			}
			rel = append(rel, related...)
		}
		o.R.Users = rel
	}
}

// BuildSetter returns an *models.TeamSetter
// this does nothing with the relationship templates
func (o TeamTemplate) BuildSetter() *models.TeamSetter {
	m := &models.TeamSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.TeamSetter
// this does nothing with the relationship templates
func (o TeamTemplate) BuildManySetter(number int) []*models.TeamSetter {
	m := make([]*models.TeamSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Team
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use TeamTemplate.Create
func (o TeamTemplate) Build() *models.Team {
	m := &models.Team{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.TeamSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use TeamTemplate.CreateMany
func (o TeamTemplate) BuildMany(number int) models.TeamSlice {
	m := make(models.TeamSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableTeam(m *models.TeamSetter) {
	if !(m.ID.IsValue()) {
		val := random_string(nil, "36")
		m.ID = omit.From(val)
	}
	if !(m.Name.IsValue()) {
		val := random_string(nil, "255")
		m.Name = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Team
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *TeamTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Team) error {
	var err error

	isUsersDone, _ := teamRelUsersCtx.Value(ctx)
	if !isUsersDone && o.r.Users != nil {
		ctx = teamRelUsersCtx.WithValue(ctx, true)
		for _, r := range o.r.Users {
			if r.o.alreadyPersisted {
				m.R.Users = append(m.R.Users, r.o.Build())
			} else {
				rel0, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachUsers(ctx, exec, rel0...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a team and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *TeamTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Team, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableTeam(opt)

	m, err := models.Teams.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a team and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *TeamTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Team {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a team and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *TeamTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Team {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple teams and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o TeamTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.TeamSlice, error) {
	var err error
	m := make(models.TeamSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple teams and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o TeamTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.TeamSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple teams and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o TeamTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.TeamSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Team has methods that act as mods for the TeamTemplate
var TeamMods teamMods

type teamMods struct{}

func (m teamMods) RandomizeAllColumns(f *faker.Faker) TeamMod {
	return TeamModSlice{
		TeamMods.RandomID(f),
		TeamMods.RandomName(f),
		TeamMods.RandomCreatedAt(f),
	}
}

// Set the model columns to this value
func (m teamMods) ID(val string) TeamMod {
	return TeamModFunc(func(_ context.Context, o *TeamTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m teamMods) IDFunc(f func() string) TeamMod {
	return TeamModFunc(func(_ context.Context, o *TeamTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m teamMods) UnsetID() TeamMod {
	return TeamModFunc(func(_ context.Context, o *TeamTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m teamMods) RandomID(f *faker.Faker) TeamMod {
	return TeamModFunc(func(_ context.Context, o *TeamTemplate) {
		o.ID = func() string {
			return random_string(f, "36")
		}
	})
}

// Set the model columns to this value
func (m teamMods) Name(val string) TeamMod {
	return TeamModFunc(func(_ context.Context, o *TeamTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m teamMods) NameFunc(f func() string) TeamMod {
	return TeamModFunc(func(_ context.Context, o *TeamTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m teamMods) UnsetName() TeamMod {
	return TeamModFunc(func(_ context.Context, o *TeamTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m teamMods) RandomName(f *faker.Faker) TeamMod {
	return TeamModFunc(func(_ context.Context, o *TeamTemplate) {
		o.Name = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m teamMods) CreatedAt(val time.Time) TeamMod {
	return TeamModFunc(func(_ context.Context, o *TeamTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m teamMods) CreatedAtFunc(f func() time.Time) TeamMod {
	return TeamModFunc(func(_ context.Context, o *TeamTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m teamMods) UnsetCreatedAt() TeamMod {
	return TeamModFunc(func(_ context.Context, o *TeamTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m teamMods) RandomCreatedAt(f *faker.Faker) TeamMod {
	return TeamModFunc(func(_ context.Context, o *TeamTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m teamMods) WithParentsCascading() TeamMod {
	return TeamModFunc(func(ctx context.Context, o *TeamTemplate) {
		if isDone, _ := teamWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = teamWithParentsCascadingCtx.WithValue(ctx, true)
	})
}

func (m teamMods) WithUsers(number int, related *UserTemplate) TeamMod {
	return TeamModFunc(func(ctx context.Context, o *TeamTemplate) {
		o.r.Users = []*teamRUsersR{{
			number: number,
			o:      related,
		}}
	})
}

func (m teamMods) WithNewUsers(number int, mods ...UserMod) TeamMod {
	return TeamModFunc(func(ctx context.Context, o *TeamTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)
		m.WithUsers(number, related).Apply(ctx, o)
	})
}

func (m teamMods) AddUsers(number int, related *UserTemplate) TeamMod {
	return TeamModFunc(func(ctx context.Context, o *TeamTemplate) {
		o.r.Users = append(o.r.Users, &teamRUsersR{
			number: number,
			o:      related,
		})
	})
}

func (m teamMods) AddNewUsers(number int, mods ...UserMod) TeamMod {
	return TeamModFunc(func(ctx context.Context, o *TeamTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)
		m.AddUsers(number, related).Apply(ctx, o)
	})
}

func (m teamMods) AddExistingUsers(existingModels ...*models.User) TeamMod {
	return TeamModFunc(func(ctx context.Context, o *TeamTemplate) {
		for _, em := range existingModels {
			o.r.Users = append(o.r.Users, &teamRUsersR{
				o: o.f.FromExistingUser(em),
			})
		}
	})
}

func (m teamMods) WithoutUsers() TeamMod {
	return TeamModFunc(func(ctx context.Context, o *TeamTemplate) {
		o.r.Users = nil
	})
}
