---
- name: Add Caddy GPG key
  ansible.builtin.apt_key:
    url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
    keyring: /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  become: true

- name: Add Caddy repository
  ansible.builtin.get_url:
    url: https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt
    dest: /etc/apt/sources.list.d/caddy-stable.list
    mode: "0644"
  become: true

- name: Install Caddy
  ansible.builtin.apt:
    name: caddy
    state: present
    update_cache: true
  become: true

- name: Configure Caddy
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    mode: "0644"
  become: true
  notify:
    - Restart Caddy
