// Code generated by BobGen mysql v0.49.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/scan"
)

// Team is an object representing the database table.
type Team struct {
	ID        string    `db:"id,pk" `
	Name      string    `db:"name" `
	CreatedAt time.Time `db:"created_at" `

	R teamR `db:"-" `

	C teamC `db:"-" `
}

// TeamSlice is an alias for a slice of pointers to Team.
// This should almost always be used instead of []*Team.
type TeamSlice []*Team

// Teams contains methods to work with the teams table
var Teams = mysql.NewTablex[*Team, TeamSlice, *TeamSetter]("teams", buildTeamColumns("teams"), teamScanMapper, []string{"id"})

// TeamsQuery is a query on the teams table
type TeamsQuery = *mysql.ViewQuery[*Team, TeamSlice]

// teamR is where relationships are stored.
type teamR struct {
	TeamGithubAccounts TeamGithubAccountSlice // team_github_accounts_ibfk_1
	Users              UserSlice              // users_ibfk_1
	// Loaded reports whether each relationship has been loaded.
	// A relationship's bool is set by Load*, Preload, ThenLoad, factory builds,
	// and to-one Attach/Insert operations. To-many Attach/Insert operations leave it unchanged.
	Loaded teamRLoaded `db:"-" `
}

// teamRLoaded tracks which relationships on Team have been loaded.
type teamRLoaded struct {
	TeamGithubAccounts bool // team_github_accounts_ibfk_1
	Users              bool // users_ibfk_1
}

func buildTeamColumns(tableName string) teamColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "name", "created_at",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return teamColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		ID:          buildTeamColumn(tableName, "id"),
		Name:        buildTeamColumn(tableName, "name"),
		CreatedAt:   buildTeamColumn(tableName, "created_at"),
	}
}

type teamColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         teamColumn
	Name       teamColumn
	CreatedAt  teamColumn
}

// Alias returns the current table alias for the columns set.
func (c teamColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (teamColumns) AliasedAs(tableName string) teamColumns {
	return buildTeamColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c teamColumns) Unqualified() teamColumns {
	return buildTeamColumns("")
}

func buildTeamColumn(alias, name string) teamColumn {
	return teamColumn{
		Expression: mysql.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type teamColumn struct {
	mysql.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c teamColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c teamColumn) ShouldOmitParens() bool {
	return true
}

// TeamSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type TeamSetter struct {
	ID        *string    `db:"id,pk" `
	Name      *string    `db:"name" `
	CreatedAt *time.Time `db:"created_at" `
}

func (s TeamSetter) SetColumns() []string {
	vals := make([]string, 0, 3)
	if s.ID != nil {
		vals = append(vals, "id")
	}
	if s.Name != nil {
		vals = append(vals, "name")
	}
	if s.CreatedAt != nil {
		vals = append(vals, "created_at")
	}
	return vals
}

func (s TeamSetter) Overwrite(t *Team) {
	if s.ID != nil {
		t.ID = func() string {
			if s.ID == nil {
				return *new(string)
			}
			return *s.ID
		}()
	}
	if s.Name != nil {
		t.Name = func() string {
			if s.Name == nil {
				return *new(string)
			}
			return *s.Name
		}()
	}
	if s.CreatedAt != nil {
		t.CreatedAt = func() time.Time {
			if s.CreatedAt == nil {
				return *new(time.Time)
			}
			return *s.CreatedAt
		}()
	}
}

func (s *TeamSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Teams.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.ID == nil {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() string {
				if s.ID == nil {
					return *new(string)
				}
				return *s.ID
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.Name == nil {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() string {
				if s.Name == nil {
					return *new(string)
				}
				return *s.Name
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.CreatedAt == nil {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() time.Time {
				if s.CreatedAt == nil {
					return *new(time.Time)
				}
				return *s.CreatedAt
			}()).WriteSQL(ctx, w, d, start)
		}))
}

func (s TeamSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("teams")...)
}

func (s TeamSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 3)

	if s.ID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "id")...),
			mysql.Arg(s.ID),
		}})
	}

	if s.Name != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "name")...),
			mysql.Arg(s.Name),
		}})
	}

	if s.CreatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "created_at")...),
			mysql.Arg(s.CreatedAt),
		}})
	}

	return exprs
}

// scan.Mapper[*T] without reflection: maps columns to fields by index.
func teamScanMapper(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*Team, error)) {
	// resolve the column positions once per query, not per row
	type target struct {
		idx int
		dst func(o *Team) any
	}
	targets := make([]target, 0, 3)
	for i, col := range cols {
		switch col {
		case "id":
			targets = append(targets, target{i, func(o *Team) any { return &o.ID }})
		case "name":
			targets = append(targets, target{i, func(o *Team) any { return &o.Name }})
		case "created_at":
			targets = append(targets, target{i, func(o *Team) any { return &o.CreatedAt }})
		}
	}

	return func(row *scan.Row) (any, error) {
			o := new(Team)
			for _, t := range targets {
				row.ScheduleScanByIndex(t.idx, t.dst(o))
			}
			return o, nil
		}, func(v any) (*Team, error) {
			return v.(*Team), nil
		}
}

// FindTeam retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindTeam(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*Team, error) {
	if len(cols) == 0 {
		return Teams.Query(
			sm.Where(Teams.Columns.ID.EQ(mysql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Teams.Query(
		sm.Where(Teams.Columns.ID.EQ(mysql.Arg(IDPK))),
		sm.Columns(Teams.Columns.Only(cols...)),
	).One(ctx, exec)
}

// TeamExists checks the presence of a single record by primary key
func TeamExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return Teams.Query(
		sm.Where(Teams.Columns.ID.EQ(mysql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Team is retrieved from the database
func (o *Team) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Teams.AfterSelectHooks.RunHooks(ctx, exec, TeamSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Teams.AfterInsertHooks.RunHooks(ctx, exec, TeamSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Teams.AfterUpdateHooks.RunHooks(ctx, exec, TeamSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Teams.AfterDeleteHooks.RunHooks(ctx, exec, TeamSlice{o})

	}

	return err
}

// primaryKeyVals returns the primary key values of the Team
func (o *Team) primaryKeyVals() bob.Expression {
	return mysql.Arg(o.ID)
}

func (o *Team) pkEQ() dialect.Expression {
	return mysql.Quote("teams", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Team
func (o *Team) Update(ctx context.Context, exec bob.Executor, s *TeamSetter) error {
	_, err := Teams.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single Team record with an executor
func (o *Team) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Teams.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Team using the executor
func (o *Team) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Teams.Query(
		sm.Where(Teams.Columns.ID.EQ(mysql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after TeamSlice is retrieved from the database
func (o TeamSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Teams.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Teams.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Teams.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Teams.AfterDeleteHooks.RunHooks(ctx, exec, o)

	}

	return err
}

func (o TeamSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("teams", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o TeamSlice) copyMatchingRows(from ...*Team) {
	fromByPK := make(map[string]*Team, len(from))
	for _, new := range from {
		// keep the first row for each key, like the nested loop did
		if _, ok := fromByPK[new.ID]; !ok {
			fromByPK[new.ID] = new
		}
	}

	for i, old := range o {
		new, ok := fromByPK[old.ID]
		if !ok {
			continue
		}
		new.R = old.R
		o[i] = new
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o TeamSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Teams.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Team:
				o.copyMatchingRows(retrieved)
			case []*Team:
				o.copyMatchingRows(retrieved...)
			case TeamSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Team or a slice of Team
				// then run the AfterUpdateHooks on the slice
				_, err = Teams.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o TeamSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Teams.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Team:
				o.copyMatchingRows(retrieved)
			case []*Team:
				o.copyMatchingRows(retrieved...)
			case TeamSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Team or a slice of Team
				// then run the AfterDeleteHooks on the slice
				_, err = Teams.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o TeamSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals TeamSetter) error {
	_, err := Teams.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o TeamSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Teams.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o TeamSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Teams.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// TeamGithubAccounts starts a query for related objects on team_github_accounts
func (o *Team) TeamGithubAccounts(mods ...bob.Mod[*dialect.SelectQuery]) TeamGithubAccountsQuery {
	return TeamGithubAccounts.Query(append(mods,
		sm.Where(TeamGithubAccounts.Columns.TeamID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os TeamSlice) TeamGithubAccounts(mods ...bob.Mod[*dialect.SelectQuery]) TeamGithubAccountsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.ID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return TeamGithubAccounts.Query(append(mods,
		sm.Where(mysql.Group(TeamGithubAccounts.Columns.TeamID).OP("IN", PKArgExpr)),
	)...)
}

// Users starts a query for related objects on users
func (o *Team) Users(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.TeamID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os TeamSlice) Users(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.ID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return Users.Query(append(mods,
		sm.Where(mysql.Group(Users.Columns.TeamID).OP("IN", PKArgExpr)),
	)...)
}

func insertTeamTeamGithubAccounts0(ctx context.Context, exec bob.Executor, teamGithubAccounts1 []*TeamGithubAccountSetter, team0 *Team) (TeamGithubAccountSlice, error) {
	for i := range teamGithubAccounts1 {
		teamGithubAccounts1[i].TeamID = func() *string { return &team0.ID }()
	}

	ret, err := TeamGithubAccounts.Insert(bob.ToMods(teamGithubAccounts1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertTeamTeamGithubAccounts0: %w", err)
	}

	return ret, nil
}

func attachTeamTeamGithubAccounts0(ctx context.Context, exec bob.Executor, count int, teamGithubAccounts1 TeamGithubAccountSlice, team0 *Team) (TeamGithubAccountSlice, error) {
	setter := &TeamGithubAccountSetter{
		TeamID: func() *string { return &team0.ID }(),
	}

	err := teamGithubAccounts1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachTeamTeamGithubAccounts0: %w", err)
	}

	return teamGithubAccounts1, nil
}

func (team0 *Team) InsertTeamGithubAccounts(ctx context.Context, exec bob.Executor, related ...*TeamGithubAccountSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	teamGithubAccounts1, err := insertTeamTeamGithubAccounts0(ctx, exec, related, team0)
	if err != nil {
		return err
	}

	team0.R.TeamGithubAccounts = append(team0.R.TeamGithubAccounts, teamGithubAccounts1...)

	for _, rel := range teamGithubAccounts1 {
		rel.R.Team = team0
		rel.R.Loaded.Team = true
	}
	return nil
}

func (team0 *Team) AttachTeamGithubAccounts(ctx context.Context, exec bob.Executor, related ...*TeamGithubAccount) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	teamGithubAccounts1 := TeamGithubAccountSlice(related)

	_, err = attachTeamTeamGithubAccounts0(ctx, exec, len(related), teamGithubAccounts1, team0)
	if err != nil {
		return err
	}

	team0.R.TeamGithubAccounts = append(team0.R.TeamGithubAccounts, teamGithubAccounts1...)

	for _, rel := range related {
		rel.R.Team = team0
		rel.R.Loaded.Team = true
	}

	return nil
}

func insertTeamUsers0(ctx context.Context, exec bob.Executor, users1 []*UserSetter, team0 *Team) (UserSlice, error) {
	for i := range users1 {
		users1[i].TeamID = func() *sql.Null[string] { v := sql.Null[string]{V: team0.ID, Valid: true}; return &v }()
	}

	ret, err := Users.Insert(bob.ToMods(users1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertTeamUsers0: %w", err)
	}

	return ret, nil
}

func attachTeamUsers0(ctx context.Context, exec bob.Executor, count int, users1 UserSlice, team0 *Team) (UserSlice, error) {
	setter := &UserSetter{
		TeamID: func() *sql.Null[string] { v := sql.Null[string]{V: team0.ID, Valid: true}; return &v }(),
	}

	err := users1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachTeamUsers0: %w", err)
	}

	return users1, nil
}

func (team0 *Team) InsertUsers(ctx context.Context, exec bob.Executor, related ...*UserSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	users1, err := insertTeamUsers0(ctx, exec, related, team0)
	if err != nil {
		return err
	}

	team0.R.Users = append(team0.R.Users, users1...)

	for _, rel := range users1 {
		rel.R.Team = team0
		rel.R.Loaded.Team = true
	}
	return nil
}

func (team0 *Team) AttachUsers(ctx context.Context, exec bob.Executor, related ...*User) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	users1 := UserSlice(related)

	_, err = attachTeamUsers0(ctx, exec, len(related), users1, team0)
	if err != nil {
		return err
	}

	team0.R.Users = append(team0.R.Users, users1...)

	for _, rel := range related {
		rel.R.Team = team0
		rel.R.Loaded.Team = true
	}

	return nil
}

type teamWhere[Q mysql.Filterable] struct {
	cols      teamColumns
	ID        mysql.WhereMod[Q, string]
	Name      mysql.WhereMod[Q, string]
	CreatedAt mysql.WhereMod[Q, time.Time]
	R         teamWhereR[Q]
}

func (teamWhere[Q]) AliasedAs(alias string) teamWhere[Q] {
	return buildTeamWhere[Q](buildTeamColumns(alias))
}

func buildTeamWhere[Q mysql.Filterable](cols teamColumns) teamWhere[Q] {
	return teamWhere[Q]{
		cols:      cols,
		ID:        mysql.Where[Q, string](cols.ID.Expression),
		Name:      mysql.Where[Q, string](cols.Name.Expression),
		CreatedAt: mysql.Where[Q, time.Time](cols.CreatedAt.Expression),
		R:         teamWhereR[Q]{cols: cols},
	}
}

// teamWhereR holds the relationship-based filters of
// teamWhere under the R namespace — mirroring the model's
// R struct — so they cannot collide with column-based filter fields.
type teamWhereR[Q mysql.Filterable] struct {
	cols teamColumns
}

// HasTeamGithubAccounts filters parents that have a matching TeamGithubAccounts using a
// correlated EXISTS subquery (semi-join). Unlike an INNER JOIN it does not
// multiply parent rows, so no DISTINCT is needed. The optional filters are
// applied to the subquery (i.e. to TeamGithubAccounts).
func (w teamWhereR[Q]) HasTeamGithubAccounts(filters ...bob.Mod[*dialect.SelectQuery]) mods.Where[Q] {
	q := mysql.Select(
		sm.Columns(mysql.Raw("1")),
		sm.From(TeamGithubAccounts.NameExpr()),
		sm.Where(TeamGithubAccounts.Columns.TeamID.EQ(w.cols.ID)),
	)
	q.Apply(filters...)
	return mods.Where[Q]{E: mysql.Exists(q)}
}

// HasUsers filters parents that have a matching Users using a
// correlated EXISTS subquery (semi-join). Unlike an INNER JOIN it does not
// multiply parent rows, so no DISTINCT is needed. The optional filters are
// applied to the subquery (i.e. to Users).
func (w teamWhereR[Q]) HasUsers(filters ...bob.Mod[*dialect.SelectQuery]) mods.Where[Q] {
	q := mysql.Select(
		sm.Columns(mysql.Raw("1")),
		sm.From(Users.NameExpr()),
		sm.Where(Users.Columns.TeamID.EQ(w.cols.ID)),
	)
	q.Apply(filters...)
	return mods.Where[Q]{E: mysql.Exists(q)}
}

// NULL-tolerant scan buffer for teamScanMapperNullable:
// on a LEFT JOIN miss every column comes back NULL, so each field uses the
// nullable version of the column type even when the column itself is NOT NULL.
type teamPreloadBuf struct {
	ID        sql.Null[string]
	Name      sql.Null[string]
	CreatedAt sql.Null[time.Time]
}

// teamScanMapperNullable maps the preloaded team
// columns (prefixed with the runtime join alias) without reflection, while
// keeping the LEFT JOIN semantics of the reflection-based mapper: a row whose
// prefixed columns are all NULL yields nil (no child), and NULL values never
// error, they just leave the zero value in the field.
func teamScanMapperNullable(prefix string) scan.Mapper[*Team] {
	return func(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*Team, error)) {
		// resolve the column names once per query, not per row
		type target struct {
			idx int
			dst func(b *teamPreloadBuf) any
		}
		targets := make([]target, 0, 3)
		for i, col := range cols {
			name, ok := strings.CutPrefix(col, prefix)
			if !ok {
				continue
			}
			switch name {
			case "id":
				targets = append(targets, target{i, func(b *teamPreloadBuf) any { return &b.ID }})
			case "name":
				targets = append(targets, target{i, func(b *teamPreloadBuf) any { return &b.Name }})
			case "created_at":
				targets = append(targets, target{i, func(b *teamPreloadBuf) any { return &b.CreatedAt }})
			}
		}

		// One scratch buffer reused for every row: before -> scan -> after runs
		// synchronously per row, the scheduled columns are fully overwritten each
		// row, and unselected columns stay zero, so a single buffer preserves the
		// per-row NULL semantics without allocating a buffer per parent row. The
		// returned child (o below) is always freshly allocated, so buf never
		// escapes past the after func.
		buf := new(teamPreloadBuf)
		return func(row *scan.Row) (any, error) {
				for _, t := range targets {
					row.ScheduleScanByIndex(t.idx, t.dst(buf))
				}
				return buf, nil
			}, func(link any) (*Team, error) {
				buf := link.(*teamPreloadBuf)

				// Same rule as the reflection mapper's row validator: the child
				// exists only if at least one of its columns is not NULL. Columns
				// not selected by the query are never scanned and stay invalid,
				// so this check also matches when only a subset is selected.
				if !(buf.ID.Valid) &&
					!(buf.Name.Valid) &&
					!(buf.CreatedAt.Valid) {
					return nil, nil
				}

				o := new(Team)
				if buf.ID.Valid {
					o.ID = buf.ID.V
				}
				if buf.Name.Valid {
					o.Name = buf.Name.V
				}
				if buf.CreatedAt.Valid {
					o.CreatedAt = buf.CreatedAt.V
				}
				return o, nil
			}
	}
}

func (o *Team) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "TeamGithubAccounts":
		rels, ok := retrieved.(TeamGithubAccountSlice)
		if !ok {
			return fmt.Errorf("team cannot load %T as %q", retrieved, name)
		}

		o.R.TeamGithubAccounts = rels
		o.R.Loaded.TeamGithubAccounts = true

		for _, rel := range rels {
			if rel != nil {
				rel.R.Team = o
				rel.R.Loaded.Team = true
			}
		}
		return nil
	case "Users":
		rels, ok := retrieved.(UserSlice)
		if !ok {
			return fmt.Errorf("team cannot load %T as %q", retrieved, name)
		}

		o.R.Users = rels
		o.R.Loaded.Users = true

		for _, rel := range rels {
			if rel != nil {
				rel.R.Team = o
				rel.R.Loaded.Team = true
			}
		}
		return nil
	default:
		return fmt.Errorf("team has no relationship %q", name)
	}
}

type teamPreloader struct{}

func buildTeamPreloader() teamPreloader {
	return teamPreloader{}
}

type teamThenLoader[Q orm.Loadable] struct {
	TeamGithubAccounts func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Users              func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildTeamThenLoader[Q orm.Loadable]() teamThenLoader[Q] {
	type TeamGithubAccountsLoadInterface interface {
		LoadTeamGithubAccounts(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type UsersLoadInterface interface {
		LoadUsers(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return teamThenLoader[Q]{
		TeamGithubAccounts: thenLoadBuilder[Q](
			"TeamGithubAccounts",
			func(ctx context.Context, exec bob.Executor, retrieved TeamGithubAccountsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadTeamGithubAccounts(ctx, exec, mods...)
			},
		),
		Users: thenLoadBuilder[Q](
			"Users",
			func(ctx context.Context, exec bob.Executor, retrieved UsersLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUsers(ctx, exec, mods...)
			},
		),
	}
}

// LoadTeamGithubAccounts loads the team's TeamGithubAccounts into the .R struct
func (o *Team) LoadTeamGithubAccounts(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.TeamGithubAccounts = nil
	o.R.Loaded.TeamGithubAccounts = false

	related, err := o.TeamGithubAccounts(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Team = o
		rel.R.Loaded.Team = true
	}

	o.R.TeamGithubAccounts = related
	o.R.Loaded.TeamGithubAccounts = true
	return nil
}

// LoadTeamGithubAccounts loads the team's TeamGithubAccounts into the .R struct
func (os TeamSlice) LoadTeamGithubAccounts(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	teamGithubAccounts, err := os.TeamGithubAccounts(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.TeamGithubAccounts = nil
		o.R.Loaded.TeamGithubAccounts = true
	}
	// O(N+M) stitch via a map keyed by the join column (key -> []parent; was O(N*M)).
	teamByKey := make(map[string][]*Team, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}

		teamByKey[o.ID] = append(teamByKey[o.ID], o)
	}

	for _, rel := range teamGithubAccounts {

		owners, ok := teamByKey[rel.TeamID]
		if !ok {
			continue
		}

		for _, o := range owners {

			rel.R.Team = o
			rel.R.Loaded.Team = true

			o.R.TeamGithubAccounts = append(o.R.TeamGithubAccounts, rel)

		}
	}

	return nil
}

// LoadUsers loads the team's Users into the .R struct
func (o *Team) LoadUsers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Users = nil
	o.R.Loaded.Users = false

	related, err := o.Users(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Team = o
		rel.R.Loaded.Team = true
	}

	o.R.Users = related
	o.R.Loaded.Users = true
	return nil
}

// LoadUsers loads the team's Users into the .R struct
func (os TeamSlice) LoadUsers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.Users(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Users = nil
		o.R.Loaded.Users = true
	}
	// O(N+M) stitch via a map keyed by the join column (key -> []parent; was O(N*M)).
	teamByKey := make(map[string][]*Team, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}

		teamByKey[o.ID] = append(teamByKey[o.ID], o)
	}

	for _, rel := range users {

		if !rel.TeamID.Valid {
			continue
		}

		owners, ok := teamByKey[rel.TeamID.V]
		if !ok {
			continue
		}

		for _, o := range owners {

			rel.R.Team = o
			rel.R.Loaded.Team = true

			o.R.Users = append(o.R.Users, rel)

		}
	}

	return nil
}

// teamC is where relationship counts are stored.
type teamC struct {
	TeamGithubAccounts *int64
	Users              *int64
}

// PreloadCount sets a count in the C struct by name
func (o *Team) PreloadCount(name string, count int64) error {
	if o == nil {
		return nil
	}

	switch name {
	case "TeamGithubAccounts":
		o.C.TeamGithubAccounts = &count
	case "Users":
		o.C.Users = &count
	}
	return nil
}

type teamCountPreloader struct {
	TeamGithubAccounts func(...bob.Mod[*dialect.SelectQuery]) mysql.Preloader
	Users              func(...bob.Mod[*dialect.SelectQuery]) mysql.Preloader
}

func buildTeamCountPreloader() teamCountPreloader {
	return teamCountPreloader{
		TeamGithubAccounts: func(mods ...bob.Mod[*dialect.SelectQuery]) mysql.Preloader {
			return countPreloader[*Team]("TeamGithubAccounts", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Teams.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(mysql.Raw("count(*)")),

					sm.From(TeamGithubAccounts.NameAsExpr()),
					sm.Where(mysql.Quote(TeamGithubAccounts.Alias(), "team_id").EQ(mysql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return mysql.Group(mysql.Select(subqueryMods...).Expression)
			})
		},
		Users: func(mods ...bob.Mod[*dialect.SelectQuery]) mysql.Preloader {
			return countPreloader[*Team]("Users", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Teams.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(mysql.Raw("count(*)")),

					sm.From(Users.NameAsExpr()),
					sm.Where(mysql.Quote(Users.Alias(), "team_id").EQ(mysql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return mysql.Group(mysql.Select(subqueryMods...).Expression)
			})
		},
	}
}

type teamCountThenLoader[Q orm.Loadable] struct {
	TeamGithubAccounts func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Users              func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildTeamCountThenLoader[Q orm.Loadable]() teamCountThenLoader[Q] {
	type TeamGithubAccountsCountInterface interface {
		LoadCountTeamGithubAccounts(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type UsersCountInterface interface {
		LoadCountUsers(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return teamCountThenLoader[Q]{
		TeamGithubAccounts: countThenLoadBuilder[Q](
			"TeamGithubAccounts",
			func(ctx context.Context, exec bob.Executor, retrieved TeamGithubAccountsCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountTeamGithubAccounts(ctx, exec, mods...)
			},
		),
		Users: countThenLoadBuilder[Q](
			"Users",
			func(ctx context.Context, exec bob.Executor, retrieved UsersCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountUsers(ctx, exec, mods...)
			},
		),
	}
}

// LoadCountTeamGithubAccounts loads the count of TeamGithubAccounts into the C struct
func (o *Team) LoadCountTeamGithubAccounts(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.TeamGithubAccounts(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.TeamGithubAccounts = &count
	return nil
}

// LoadCountTeamGithubAccounts loads the count of TeamGithubAccounts for a slice in a single batch query
func (os TeamSlice) LoadCountTeamGithubAccounts(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs
	PKArgSlice := make([]bob.Expression, 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		PKArgSlice = append(PKArgSlice, mysql.Arg(o.ID))
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    string
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			TeamGithubAccounts.Columns.TeamID.As("id"),
			mysql.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(TeamGithubAccounts.NameAsExpr()),

		// WHERE fk IN (parent PKs) — psql single-column FK uses `= ANY(array)` (see PKArgExpr above)
		sm.Where(TeamGithubAccounts.Columns.TeamID.OP("IN", PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(TeamGithubAccounts.Columns.TeamID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		mysql.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[string]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.TeamGithubAccounts = &count
	}

	return nil
}

// LoadCountUsers loads the count of Users into the C struct
func (o *Team) LoadCountUsers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.Users(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.Users = &count
	return nil
}

// LoadCountUsers loads the count of Users for a slice in a single batch query
func (os TeamSlice) LoadCountUsers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs
	PKArgSlice := make([]bob.Expression, 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		PKArgSlice = append(PKArgSlice, mysql.Arg(o.ID))
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    string
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			Users.Columns.TeamID.As("id"),
			mysql.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(Users.NameAsExpr()),

		// WHERE fk IN (parent PKs) — psql single-column FK uses `= ANY(array)` (see PKArgExpr above)
		sm.Where(Users.Columns.TeamID.OP("IN", PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(Users.Columns.TeamID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		mysql.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[string]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.Users = &count
	}

	return nil
}

type teamJoins[Q dialect.Joinable] struct {
	typ                string
	TeamGithubAccounts modAs[Q, teamGithubAccountColumns]
	Users              modAs[Q, userColumns]
}

func (j teamJoins[Q]) aliasedAs(alias string) teamJoins[Q] {
	return buildTeamJoins[Q](buildTeamColumns(alias), j.typ)
}

func buildTeamJoins[Q dialect.Joinable](cols teamColumns, typ string) teamJoins[Q] {
	return teamJoins[Q]{
		typ: typ,
		TeamGithubAccounts: modAs[Q, teamGithubAccountColumns]{
			c: TeamGithubAccounts.Columns,
			f: func(to teamGithubAccountColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, TeamGithubAccounts.NameExpr().As(to.Alias())).On(
						to.TeamID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Users: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.NameExpr().As(to.Alias())).On(
						to.TeamID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
