name: "Ansible CI"
on:
  push:
    branches: [main]
    paths:
      - "provisioning/ansible/**"
      - ".github/workflows/ansible-ci.yaml"
  pull_request:
    branches: [main]
    paths:
      - "provisioning/ansible/**"
      - ".github/workflows/ansible-ci.yaml"
  workflow_dispatch:

defaults:
  run:
    working-directory: provisioning/ansible
    shell: bash

jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Lint Ansible Playbooks and Roles
        run: uv run ansible-lint ./ ./roles/
