name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  GOEXPERIMENT: "synctest"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go build -o out/server ./cmd/server

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: golangci/golangci-lint-action@v7
        with:
          version: latest

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go test -cover -race ./...

  go-generate:
    name: Go Code Generation
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    services:
      db:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: portal
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Init DB
        run: |
          docker exec -i $(docker ps -q) mysql -u root -ppassword portal < ./server/schema.sql
        shell: bash

      - name: Go generate
        run: go generate ./...

      - name: Commit and push changes
        run: |
          if [[ -z $(git status --porcelain) ]]; then
            exit 0
          fi
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add .
          git commit -m "Go code generation"

          # Handle PR and push events differently
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            # For PRs, push to the PR branch (head ref)
            git push origin HEAD:${{ github.head_ref }}
          else
            # For direct pushes, push to the current branch
            git push origin HEAD:${{ github.ref_name }}
          fi
        shell: bash
