name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          # go-version-file: go.mod
      - run: go install golang.org/dl/go1.24rc3@latest && go1.24rc3 download
      - run: go1.24rc3 build -o out/server ./cmd/server
      # - run: go build -o out/server ./cmd/server

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          # go-version-file: go.mod
      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.62

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          # go-version-file: go.mod
      - run: go install golang.org/dl/go1.24rc3@latest && go1.24rc3 download
      - run: go1.24rc3 test -cover -race ./...
      # - run: go test -cover -race ./...
